"""add job certificate_title and event_name

Revision ID: 5d32a190fea2
Revises: 525c1946cc95
Create Date: 2026-10-09 10:14:48.402781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d32a190fea2'
down_revision: Union[str, Sequence[str], None] = '525c1946cc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('certificate_title', sa.String(length=100), server_default='CERTIFICATE OF ACHIEVEMENT', nullable=False))
    op.add_column('jobs', sa.Column('event_name', sa.String(length=150), server_default='the program', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'event_name')
    op.drop_column('jobs', 'certificate_title')
    # ### end Alembic commands ###
